Bookstore/Controllers/ShoppingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Bookstore.Controllers
{
    public class ShoppingController : Controller
    {
        private IShoppingRepository repo { get; set; }
        private Basket basket { get; set; }

        public ShoppingController(IShoppingRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }
        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Shopping());
        }

        [HttpPost]
        public IActionResult Checkout(Shopping shopping)
        {
            if (basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your basket is empty!");
            }

            if(ModelState.IsValid)
            {
                shopping.Lines = basket.Items.ToArray();
                repo.SaveShopping(shopping);
                basket.ClearBasket();

                return RedirectToPage("/ShoppingCompleted");
            }
            else
            {
                return View();
            }

        }
    }
}

Bookstore/Pages/ShoppingCart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bookstore.Infrastructure;
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Bookstore.Pages
{
    public class ShoppingCartModel : PageModel
    {
        private IBookstoreRepository repo { get; set; }

        public Basket basket { get; set; }
        public string ReturnUrl { get; set; }

        public ShoppingCartModel (IBookstoreRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Books b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            basket.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            basket.RemoveItem(basket.Items.First(x => x.Books.BookId == bookId).Books);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

Bookstore/Pages/ShoppingCompleted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Bookstore.Pages
{
    public class ShoppingCompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Bookstore/Pages/ShoppingCart.cshtml
@page
@model Bookstore.Pages.ShoppingCartModel
@{
}

<h1> Your Cart </h1>

<table class="table table-bordered table-striped">

    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var i in Model.basket.Items)
         {
            <tr>
                <td>@i.Books.Title</td>
                <td>@i.Quantity</td>
                <td>$@i.Books.Price</td>
                <td>$@((i.Quantity * @i.Books.Price).ToString("#,##0.00"))</td>

                <td class="text-center">
                    <form method="post" asp-page-handler="Remove">
                        <input type="hidden" name="bookId" value="@i.Books.BookId" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                    </form>
                </td>
            </tr>

         }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total: </td>
            <td>$@Model.basket.CalculateTotal().ToString("#,##0.00")</td>
        </tr>

    </tfoot>

</table>

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-controller="Shopping" asp-action="Checkout">Checkout</a>
</div>

Bookstore/Pages/ShoppingCompleted.cshtml
@page
@model Bookstore.Pages.ShoppingCompletedModel
@{
}

<div class="text-centet">
    <h2>Thanks, your order will make a difference.</h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

Bookstore/Pages/_ShoppingCartLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        BOOK STORE
    </div>

    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>