Bookstore/Components/ShoppingCartSummaryViewComponent.cs
using System;
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bookstore.Components
{
    public class ShoppingCartSummaryViewComponent : ViewComponent
    {
        private Basket basket;

        public ShoppingCartSummaryViewComponent(Basket basketService)
        {
            basket = basketService;
        }

        public IViewComponentResult Invoke()
        {
            return View(basket);
        }
    }
}

Bookstore/Properties/TypesViewComponent.cs
using System;
using System.Linq;
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bookstore.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public TypesViewComponent (IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {

            ViewBag.SelectedType = RouteData.Values["bookType"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

Bookstore/Views/Shared/BookSummary.cshtml
@{
}
@model Books

<div class="card card-outline-primary m-1 p-1">

    <div class="bg-light p-1">
        <h3>@Model.Title</h3>

        <span class="badge bg-info" style="float:right">
            Category: @Model.Category
        </span>
    </div>


    <ul>
        <li>Author: @Model.Author</li>
        <li>Publisher: @Model.Publisher</li>
        <li>ISBN: @Model.ISBN</li>
        <li>Classification: @Model.Classification</li>
        <li>PageCount: @Model.PageCount</li>
        <li>Price: $@Model.Price</li>
    </ul>

    <form method="post" asp-page="/ShoppingCart">
        <input type="hidden" asp-for= "@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
    
        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Add To Cart</button>
        </span>
    </form>
</div>

Bookstore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/site.css" />
    <script src="https://kit.fontawesome.com/47da3a3b36.js" crossorigin="anonymous"></script>

</head>
<body>
    <div class="bg-dark text-white p-2">
        <div class="row">
            <span class="navbar-brand m-lg-2">BOOK STORE</span>
            <div class="col-6 text-right">
                <vc:shopping-cart-summary />
            </div>
        </div>
    </div>

    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:types></vc:types>
        </div>

        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>